"""Hand-authored 3/4-back parts (text grids)."""
from blib import blk_rows

# hood from behind, head tilted up to the poster; brim tip, hair tuft, nose tip and jaw peek past the rim (right)
HEAD_B34 = """
......########.........
....##AAAABBBB##.......
...#AAAAABBBBBBB##.....
..#AAAAACBBBBBBBBB#h#..
.#AAAAAACBBBBBBBCCB#hh#
.#AAAAABCBBBBBBCCCB#sa#
#AAAAABBCBBBBBCCCDB#ss#
#AAAABBBCBBBBBCCCDB#sd#
#AAAABBBCBBBBCCCDDB#d#.
#BBBBBBBCBBBBCCCDDB#f#.
#BBBBBBCCBBBCCCDDDB##..
#BBBBBBCBBBBCCCDDDB#...
#CBBBBBCBBBCCCDDDB#....
.#CBBBBCBBBCCCDDDB#....
.#CCBBBCBBCCCDDDDB#....
..#CCBCCBCCCDDDDD#.....
..#DCCCCCCCCDDDDDE#....
.#DDDCCCCCCCDDDDEEE#...
#EDDDDDDDDDDDDDEEEEE#..
"""

# back of the hoodie, both hands in the front pocket, elbows out. origin x=14, y=31
TORSO_B34 = (14, 31, """
.......#BBBBBBBBBBBBBBBBBB#.....
......#BAAAABBBBBBBBBCDDCBBC#...
.....#BC#AAAABBBBBBBBCDD#BBBC#..
.....#BC#AAABBBBBBBBBCDD#BBBC#..
....#BCC#AABBBBBBBBBCCDD#BBBCD#.
....#CCC#ABBBBBBCBBBCCDD#BBCCD#.
....#CCD#ABBBBBBCBBBCCDE#BBCCD#.
....#CCD#BBBBBBBCBBBCCDE#BCCCD#.
....#CDD#BBBBBBBCBBCCCDE#BCCDD#.
...#CDD#BBBBBBBBCBBCCCDDE#BCCDD#
...#DDE#BBBBBBBBCBCCCCDDE#CCDDE#
...#DEE#BBBBBBBBCBCCCCDEE#CDDEE#
....#EE#BBBBBBBCCBCCCDDEE#DEEE#.
.....###BBBBBBCCBCCCDDDEE#####..
.......#BBBBBBCCBCCCDDDEE#......
.......#CBBBBBCCBCCCDDDEE#......
.......#EEEEEEEEEEEEEEEEE#......
.......#CCCCCCCCCCCDDDDEE#......
........#################.......
""")


def rows_of(part):
    x0, y0, text = part
    r = blk_rows(text)
    wd = max(len(s) for s in r)
    bad = [(i, len(s)) for i, s in enumerate(r) if len(s) != wd]
    if bad:
        raise ValueError('ragged rows %r' % bad)
    return x0, y0, r


if __name__ == '__main__':
    for n in ('HEAD_B34',):
        r = blk_rows(globals()[n])
        print(n, len(r), set(len(s) for s in r))
    print('TORSO_B34', rows_of(TORSO_B34)[2].__len__(), set(len(s) for s in rows_of(TORSO_B34)[2]))

HEAD_B34_UP = """
.....########..........
...##AAAAABBB##........
..#AAAAAABBBBBB#h#.....
.#AAAAAACBBBBBBB#hh##..
.#AAAAACBBBBBBBCB#hsa#.
#AAAAABCBBBBBBCCB#ssss#
#AAAABBCBBBBBBCCDB#sdd#
#AAAABBCBBBBBCCCDB#dd#.
#AAABBBCBBBBCCCDDB#fd#.
#BBBBBBCBBBBCCCDDDB#f#.
#BBBBBCCBBBBCCCDDDB##..
#BBBBBCBBBBCCCDDDDB#...
#CBBBBCBBBCCCDDDDB#....
.#CBBBCBBBCCCDDDDB#....
.#CCBBCBBCCCDDDDDB#....
..#CCCCBCCCDDDDDD#.....
..#DCCCCCCCDDDDDDE#....
.#DDDCCCCCCDDDDDEEE#...
#EDDDDDDDDDDDDDEEEEE#..
"""
