"""Hand-authored part blocks (text grids). Each part: (x0, y0, rows) in canonical frame coords."""
from blib import blk_rows

# slouched hoodie torso, canonical hip centre (30,47); block origin x=20
TORSO_SLOUCH = (20, 32, """
.....#BBBBBBBC#......
...#ABBBBBBBBCC#.....
..#ABBBBBBBBCCC#.....
..#ABBBBBBBBCCC#.....
..#ABBBBBBBBCCCD#....
..#ABBBBBBBBCCCD#....
..#ABBBBBBBCCCCD#....
..#ABBBBBBBCCCCDD#...
...#BBBBBBBCCCCDD#...
...#BBBBBBBCCCCDDD#..
...#BBBBBBCCCCCDDD#..
...#BBBBBBCCCCCDDD#..
...#BBBBBBCCCCCDDD#..
...#BBBBBBCCCCDDDD#..
...#BBBBBCCCCCDDDD#..
....#EEEEEEEEEEEEE#..
....#CCCCCCCCCDDD#...
.....############....
""")

# near arm, hand tucked into the kangaroo pocket (drawn over TORSO_SLOUCH)
ARM_POCKET = (20, 33, """
.......#####.........
......#ABBBC#........
.....#ABBBBCD#.......
.....#ABBBBCD#.......
.....#ABBBCCD#.......
....#ABBBCCD#........
....#ABBBCCD#........
....#ABBCCD#.........
....#ABBCCD#######...
....#ABCCCBBBBBB#....
....#BCCCCCCCCCC#....
.....#DDDDDDDDDD#....
......##########.....
...............#.....
""")


def rows_of(part):
    x0, y0, text = part
    r = blk_rows(text)
    wd = max(len(s) for s in r)
    bad = [(i, len(s)) for i, s in enumerate(r) if len(s) != wd]
    if bad:
        raise ValueError('ragged rows %r' % bad)
    return x0, y0, r

TORSO_SLOUCH2 = (18, 32, """
......#BBBBBBBBCC#......
.....#ABBBBBBBBCCC#.....
....#ABBBBBBBBBCCC#.....
...#ABBBBBBBBBBCCCD#....
...#ABBBBBBBBBBCCCD#....
...#ABBBBBBBBBCCCCD#....
...#ABBBBBBBBBCCCCD#....
...#ABBBBBBBBBCCCCDD#...
...#BBBBBBBBBCCCCCDD#...
....#BBBBBBBBCCCCCDDD#..
....#BBBBBBBBCCCCCDDD#..
....#CBBBBBBCCCCCCDDD#..
....#DCBBBBBCCCCCCDDD#..
....#BDCCBBCCCCCCCDDD#..
.....#BBDDCCCCCCCCDDD#..
.....#EEEEEEEEEEEEEEE#..
.....#CCCCCCCCCCCDDD#...
......##############....
""")

ARM_POCKET2 = (18, 33, """
.........######.........
........#ABBBBC#........
.......#ABBBBBCD#.......
.......#ABBBBBCD#.......
.......#ABBBBCD#........
......#ABBBBCD#.........
......#ABBBCCD#.........
......#ABBBCCD#.........
.....#ABBBCCDC#######...
.....#ABBCCCBBBBBBBB#...
.....#BBCCCDCCCCCCCC#...
......#DDDDDDDDDDDDD#...
.......#############....
...................#....
""")

# boxing glove hanging cuff-up by its lace (thumb side toward +x). Lace attach point = (4, 0)
GLOVE_R = """
..#####..
..#bcV#..
..#bcV#..
.##LLl##.
#bbccvvV#
#bccccvV#
#bcccvvV#
#ccccvVV#
#cccvvVZ#
#vvvvVVZ#
.#VVVZZ#.
..#####..
"""

GLOVE2 = """
..####..
..#bV#..
.##LL##.
#bbccvV#
#bcccvV#
#bccvvV#
#cccvVV#
#vcvvVZ#
#vvvVVZ#
.#VVZZ#.
..####..
"""

TORSO_UP = (18, 30, """
.......##########.......
......#ABBBBBBBCC#......
.....#ABBBBBBBBCCC#.....
....#ABBBBBBBBBCCCD#....
....#ABBBBBBBBBCCCD#....
....#ABBBBBBBBBCCCDD#...
....#ABBBBBBBBCCCCDD#...
....#ABBBBBBBBCCCCDD#...
....#ABBBBBBBBCCCCDD#...
....#ABBBBBBBBCCCCDD#...
....#ABBBBBBBBCCCCEE#...
.....#BBBBBBBBCCCCDE#...
.....#BBBBBBBBCCCEDD#...
.....#BBBBBBBBCCCEDDD#..
.....#BBBBBBBCCCCEDDD#..
.....#CBBBBBBCCCEDDDD#..
.....#BBBBBBCCCCEDDDD#..
.....#EEEEEEEEEEEEEEE#..
......#CCCCCCCCCCDDD#...
.......#############....
""")

FIST = """
.###.
#ass#
#sdd#
#fdf#
.###.
"""

HAND_OPEN = """
.###..
#asd#.
#sdd##
#fdddf#
.#fff#.
..###..
"""

FIST6 = """
.####.
#aasd#
#sdsd#
#dfdf#
#fffg#
.####.
"""

FIST7 = """
.#####.
#aasss#
#sdsdd#
#sfsdf#
#dfdff#
#ffffg#
.#####.
"""

HAND_OPEN2 = """
.###..
#asd#.
#sddf#
#sdff#
.#dff#
..###.
"""
