"""Burak's raised lead glove at 1x - the Pokémon fist, gloved - lit from the upper left.

A boxing mitt held up in front of his chest, back of the hand to us: the padded fist is the big
rounded mass, and the thumb a separate lobe pressed against its left side (toward his body's
centre, where a left thumb sits), ringed off in ink so it reads at a glance; then the cuff. Four
blues and the one accent: A shine, B light, C base, D shadow, E deep; K ink; '.' keep.
"""
LEGEND = {"K": "#000000", "A": "#6BA8E0", "B": "#3883C9", "C": "#2464BD", "D": "#162FBB",
          "E": "#0E1C72"}
GLOVE_AT = (110, 40)

GLOVE = """
.......KKKKKKKK..........
.....KKBBBBBBCCKK........
....KBBAAABBBBCCCK.......
...KBAAABBBBBBCCCCK......
...KBAABBBBBBBCCCCDK.....
..KBABBBBBBBBCCCCCDDK....
..KBBBBBBBBBBCCCCCDDK....
..KBBBBBBBBBCCCCCCDDDK...
..KBBBBBBBBCCCCCCCDDDK...
.KKKBBBBBBCCCCCCCCDDDK...
KBBKKBBBBCCCCCCCCDDDDK...
KBABBKBBCCCCCCCCDDDDDK...
KBBBBBKCCCCCCCCCDDDDEK...
KBBBCCKCCCCCCCCDDDDDEK...
.KBCCDKCCCCCCCDDDDDEEK...
.KCCDDKCCCCCCDDDDDDEK....
..KDDKCCCCCDDDDDDDEEK....
...KKDCCDDDDDDDDDEEK.....
....KDDDDDDDDDDDEEK......
....KKKKKKKKKKKKKKK......
....KEEEDDDDDDDEEEK......
....KEDDDDDDDDDDDEK......
....KEEEDDDDDDDEEEK......
....KEEEEEEEEEEEEEK......
....KKKKKKKKKKKKKKK......
"""
