"""Generates burak_head.py's FACE grid from a few decisions, so the face can be redrawn by editing
numbers rather than 700 characters: the profile, the jaw, the tone zones, the features.

    python make_burak_face.py        rewrites burak_head.py (a file in this folder; no Assets)
"""
import os

W = 36
ROWS = 22
# per row: (first skin col after the left line, last skin col before the profile line)
LEFT = {r: 6 for r in range(15)}
LEFT.update({15: 7, 16: 8, 17: 9, 18: 10, 19: 12, 20: 14})
RIGHT = {**{r: 30 for r in range(7)}, 7: 31, 8: 31, 9: 30, 10: 31, 11: 32, 12: 32, 13: 30, 14: 30,
         15: 30, 16: 29, 17: 29, 18: 29, 19: 28, 20: 26}


def zone(c):
    """Broad lighting from the upper left: the cheek and temple lit, the front plane at base, the
    profile side a step down."""
    if c <= 19:
        return "b"
    if c <= 25:
        return "c"
    return "d"


grid = [["."] * W for _ in range(ROWS)]
for r in range(ROWS - 1):
    lo, hi = LEFT[r], RIGHT[r]
    grid[r][lo] = "K"
    for c in range(lo + 1, hi + 1):
        grid[r][c] = zone(c)
    grid[r][hi + 1] = "K"
# the line under the chin
for c in range(15, 28):
    grid[ROWS - 1][c] = "K"


def put(r, c0, s):
    for i, ch in enumerate(s):
        grid[r][c0 + i] = ch


# The features, row by row (rows 7-17), drawn whole: at this size the brows, eyes and nose are one
# design and have to be placed together. Matt's intro sheet is the model for the eye: a black lid,
# a black iris with one glint on its lit upper left, a black lower edge - Burak's glint is his
# lightest skin tone, because his sheet holds no white. The brows are black and dip into the nose.
FEATURES = {
    7: "KbcfcKKbbbbbbKKKKKKbcccccKKKKKddK...",
    8: "KbcfdKKbbbbbbbbbbbKKKcccKKddddddK...",
    9: "KbcfdKKbbbbbbbKKKKKKccccccKKKddK....",
    10: "KbcdeKKbbbbbbbKKaKKKccbcccaKKddddK..",
    11: "KbcddKKbbbbbbbbKKKKbccbccddKKbbbbdK.",
    12: ".KcdK.KbbbbaaaaeeeebcccccddddbccddK.",
    13: ".KKKK.KbbbbbbbbbbbbbcccceeeeefeK....",
    14: "......KbbbbbbbbbbbbbccccccdddddK....",
    15: ".......KccbbbbbbbbbbccccccdddddK....",
    16: "........KcdbbbbbbbbbfKKKKKfdddK.....",
    17: ".........KddbbbbbbbbbbbbbbbdddK.....",
}
for r, row in FEATURES.items():
    assert len(row) == W, (r, len(row))
    grid[r] = list(row)
# chin lit, the underside of the jaw in shadow
put(18, 20, "eeee")
put(19, 20, "bbb")
put(18, 11, "dde")
put(19, 13, "eed")
put(20, 15, "eedddd")
# the ear, over the hair (columns 0-5)
ear = {5: ".KKK..", 6: "KbbcK."}
for r, s in ear.items():
    put(r, 0, s)

rows = ["".join(g) for g in grid]
assert all(len(x) == W for x in rows)
HEAD = '''"""Burak's head at 1x (sprite scale), three-quarters facing right, lit from the upper LEFT - the one
light every VS pose shares (STYLE.md). GENERATED by make_burak_face.py; edit that, not this.

Drawn in the house face style - Eric's sheet is the model: heavy black brows pressed low, black eye
bars, no sclera and no catchlight (his sheet holds no white), a compact chibi face under a big head.
Broad lighting: the cheek and temple take the light, the front plane is at base, the profile side a
step down.

Legend: K ink, a..f the approved skin ramp light to dark, '.' keep. Origin in the 1x canvas: FACE_AT.
The ear is columns 0-5.
"""
SK_HI, SK_LT, SK, SK_MD, SK_SH, SK_DK = "#F0BE8C", "#E2A874", "#D79864", "#BE8254", "#AC714F", "#7A4A33"
LEGEND = {"K": "#000000", "a": SK_HI, "b": SK_LT, "c": SK, "d": SK_MD, "e": SK_SH, "f": SK_DK,
          "H": "#1A1A22", "h": "#2E2E3A"}
FACE_AT = (86, 19)
EAR_COLS = 6

FACE = """
''' + "\n".join(rows) + '''
"""
'''
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "burak_head.py"), "w",
     encoding="utf-8").write(HEAD)
print("\n".join(rows))
