"""Hand-made pixel fonts. Rows are top-aligned; 'X' = ink."""


def _g(s):
    return [r for r in s.split()]


# ------------------------------------------------------------------ 5x7 (+ lowercase with descenders)
F57 = {
    'A': _g(".XXX. X...X X...X XXXXX X...X X...X X...X"),
    'B': _g("XXXX. X...X X...X XXXX. X...X X...X XXXX."),
    'C': _g(".XXX. X...X X.... X.... X.... X...X .XXX."),
    'D': _g("XXXX. X...X X...X X...X X...X X...X XXXX."),
    'E': _g("XXXXX X.... X.... XXXX. X.... X.... XXXXX"),
    'F': _g("XXXXX X.... X.... XXXX. X.... X.... X...."),
    'G': _g(".XXX. X...X X.... X.XXX X...X X...X .XXXX"),
    'H': _g("X...X X...X X...X XXXXX X...X X...X X...X"),
    'I': _g("XXX .X. .X. .X. .X. .X. XXX"),
    'K': _g("X...X X..X. X.X.. XX... X.X.. X..X. X...X"),
    'L': _g("X.... X.... X.... X.... X.... X.... XXXXX"),
    'M': _g("X...X XX.XX X.X.X X.X.X X...X X...X X...X"),
    'N': _g("X...X X...X XX..X X.X.X X..XX X...X X...X"),
    'O': _g(".XXX. X...X X...X X...X X...X X...X .XXX."),
    'P': _g("XXXX. X...X X...X XXXX. X.... X.... X...."),
    'R': _g("XXXX. X...X X...X XXXX. X.X.. X..X. X...X"),
    'S': _g(".XXXX X.... X.... .XXX. ....X ....X XXXX."),
    'T': _g("XXXXX ..X.. ..X.. ..X.. ..X.. ..X.. ..X.."),
    'U': _g("X...X X...X X...X X...X X...X X...X .XXX."),
    'V': _g("X...X X...X X...X X...X X...X .X.X. ..X.."),
    'W': _g("X...X X...X X...X X.X.X X.X.X X.X.X .X.X."),
    'Y': _g("X...X X...X .X.X. ..X.. ..X.. ..X.. ..X.."),
    '0': _g(".XXX. X...X X..XX X.X.X XX..X X...X .XXX."),
    '1': _g(".X. XX. .X. .X. .X. .X. XXX"),
    '2': _g(".XXX. X...X ....X ...X. ..X.. .X... XXXXX"),
    '4': _g("...X. ..XX. .X.X. X..X. XXXXX ...X. ...X."),
    '7': _g("XXXXX ....X ...X. ..X.. ..X.. ..X.. ..X.."),
    '#': _g(".X.X. .X.X. XXXXX .X.X. XXXXX .X.X. .X.X."),
    '@': _g(".XXX. X...X X.XXX X.X.X X.XXX X.... .XXXX"),
    '!': _g("X X X X X . X"),
    '.': _g(". . . . . . X"),
    ':': _g(". . X . . X ."),
    '-': _g("... ... ... XXX ... ... ..."),
    ' ': _g("... ... ... ... ... ... ..."),
    'a': _g("..... ..... .XXX. ....X .XXXX X...X .XXXX"),
    'e': _g("..... ..... .XXX. X...X XXXXX X.... .XXX."),
    'i': _g(".X. ... XX. .X. .X. .X. XXX"),
    'n': _g("..... ..... XXXX. X...X X...X X...X X...X"),
    'o': _g("..... ..... .XXX. X...X X...X X...X .XXX."),
    'r': _g("..... ..... X.XX. XX..X X.... X.... X...."),
    't': _g(".X.. .X.. XXXX .X.. .X.. .X.X ..X."),
    'u': _g("..... ..... X...X X...X X...X X..XX .XX.X"),
    'v': _g("..... ..... X...X X...X X...X .X.X. ..X.."),
    'y': _g("..... ..... X...X X...X X...X X..XX .XX.X ....X .XXX."),
    'h': _g("X.... X.... XXXX. X...X X...X X...X X...X"),
    'g': _g("..... ..... .XXXX X...X X...X X..XX .XX.X ....X .XXX."),
    'l': _g("XX. .X. .X. .X. .X. .X. XXX"),
    's': _g("..... ..... .XXXX X.... .XXX. ....X XXXX."),
    'k': _g("X... X... X..X X.X. XX.. X.X. X..X"),
    'p': _g("..... ..... XXXX. X...X X...X X...X XXXX. X.... X...."),
    'm': _g("..... ..... XX.X. X.X.X X.X.X X.X.X X...X"),
    'd': _g("....X ....X .XXXX X...X X...X X...X .XXXX"),
    'c': _g("..... ..... .XXX. X.... X.... X.... .XXX."),
    'f': _g("..XX .X.. XXXX .X.. .X.. .X.. .X.."),
}

# ------------------------------------------------------------------ 3x5 (tiny signage)
F35 = {
    'A': _g("XXX X.X XXX X.X X.X"),
    'B': _g("XX. X.X XX. X.X XX."),
    'C': _g("XXX X.. X.. X.. XXX"),
    'D': _g("XX. X.X X.X X.X XX."),
    'E': _g("XXX X.. XX. X.. XXX"),
    'F': _g("XXX X.. XX. X.. X.."),
    'G': _g("XXX X.. X.X X.X XXX"),
    'H': _g("X.X X.X XXX X.X X.X"),
    'I': _g("XXX .X. .X. .X. XXX"),
    'K': _g("X.X X.X XX. X.X X.X"),
    'L': _g("X.. X.. X.. X.. XXX"),
    'M': _g("X...X XX.XX X.X.X X...X X...X"),
    'N': _g("X..X XX.X X.XX X..X X..X"),
    'O': _g("XXX X.X X.X X.X XXX"),
    'P': _g("XXX X.X XXX X.. X.."),
    'R': _g("XX. X.X XX. X.X X.X"),
    'S': _g("XXX X.. XXX ..X XXX"),
    'T': _g("XXX .X. .X. .X. .X."),
    'U': _g("X.X X.X X.X X.X XXX"),
    'V': _g("X.X X.X X.X X.X .X."),
    'W': _g("X...X X...X X.X.X X.X.X .X.X."),
    'Y': _g("X.X X.X .X. .X. .X."),
    '0': _g("XXX X.X X.X X.X XXX"),
    '1': _g(".X. XX. .X. .X. XXX"),
    '2': _g("XX. ..X .X. X.. XXX"),
    '4': _g("X.X X.X XXX ..X ..X"),
    '7': _g("XXX ..X .X. .X. .X."),
    '#': _g(".X.X. XXXXX .X.X. XXXXX .X.X."),
    '@': _g("XXXX X..X X.XX X... XXXX"),
    '!': _g("X X X . X"),
    '/': _g("..X ..X .X. X.. X.."),
    '-': _g("... ... XXX ... ..."),
    ' ': _g(".. .. .. .. .."),
    'a': _g("... XX. .XX X.X .XX"),
    'f': _g(".X X. XX X. X."),
    'k': _g("X.. X.X XX. X.X X.X"),
}
