extends RefCounted
# Generated by art_source/jordan_puppets/jp_ship.py - do not edit by hand; re-run it instead.
#
# BACK: where each puppet's string ties on, between the shoulder blades, for every frame of every
# puppet sheet (res://Assets/Characters/Jordan/Puppets/<key>/<sheet>.png): texels on that frame,
# (0, 0) its top-left, on the UNFLIPPED sheet (mirror x as frame_width - 1 - x when flipped).
# On front views the point is behind the body: draw the string UNDER the sprite. On Greyson's
# back views (greyson_pose_a, greyson_pose_c) his back faces the camera and the ring is drawn
# there. null: not placed on that frame (the tumbling juggle frames): use the fallback.

const BACK := {
	&"greyson": {
		&"greyson_idle": [Vector2(57, 57), Vector2(57, 56), Vector2(57, 56), Vector2(57, 57)],
		&"greyson_pose_a": [Vector2(57, 61), Vector2(57, 61), Vector2(57, 61)],
		&"greyson_pose_b": [Vector2(57, 57), Vector2(57, 57), Vector2(57, 57)],
		&"greyson_pose_c": [Vector2(57, 61), Vector2(57, 61), Vector2(57, 61)],
		&"greyson_pose_hit": [Vector2(57, 57), Vector2(57, 57)],
		&"greyson_spirit": [Vector2(57, 57), Vector2(57, 57), Vector2(57, 57), Vector2(57, 57)],
		&"greyson_hit": [Vector2(55, 57), Vector2(56, 57)],
		&"greyson_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
		&"greyson_defeat": [Vector2(54, 58), Vector2(56, 61), Vector2(57, 68), Vector2(57, 68), Vector2(57, 68)],
	},
	&"matt": {
		&"matt_idle": [Vector2(48, 58), Vector2(48, 58), Vector2(48, 58), Vector2(48, 58)],
		&"matt_yell_tell": [Vector2(48, 57), Vector2(48, 57)],
		&"matt_roar": [Vector2(48, 57), Vector2(48, 58), Vector2(49, 58), Vector2(47, 59)],
		&"matt_hit": [Vector2(48, 61), Vector2(48, 62)],
		&"matt_defeat": [Vector2(48, 58), Vector2(48, 58), Vector2(48, 62), Vector2(48, 68), Vector2(48, 68), Vector2(48, 68)],
	},
	&"burak": {
		&"burak_idle": [Vector2(48, 58), Vector2(48, 59), Vector2(48, 59), Vector2(48, 58)],
		&"burak_throw": [Vector2(48, 60), Vector2(48, 57), Vector2(48, 58), Vector2(48, 59)],
		&"burak_fire": [Vector2(48, 58), Vector2(48, 58), Vector2(48, 58)],
		&"burak_broken": [Vector2(47, 60), Vector2(48, 60), Vector2(49, 60), Vector2(48, 60)],
		&"burak_hit": [Vector2(46, 58), Vector2(47, 59)],
		&"burak_boss_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
		&"burak_defeat": [Vector2(46, 58), Vector2(49, 60), Vector2(48, 63), Vector2(48, 67), Vector2(48, 67), Vector2(48, 67)],
	},
	&"danny": {
		&"danny_sumo_idle": [Vector2(88, 60), Vector2(88, 60), Vector2(88, 60), Vector2(88, 60)],
		&"danny_sumo_jump": [Vector2(88, 83), Vector2(88, 62), Vector2(88, 83)],
		&"danny_sumo_air": [Vector2(82, 72), Vector2(86, 70), Vector2(93, 72), Vector2(89, 70)],
		&"danny_sumo_slam": [Vector2(88, 65), Vector2(88, 84), Vector2(88, 62)],
		&"danny_sumo_hit": [Vector2(87, 62), Vector2(88, 61)],
		&"danny_sumo_defeat": [Vector2(90, 60), Vector2(88, 65), Vector2(88, 70), Vector2(88, 71)],
	},
	&"eric": {
		&"eric_entrance": [Vector2(131, 158), Vector2(131, 160), Vector2(131, 159), Vector2(131, 160)],
		&"eric_sheet_v2": [Vector2(128, 158), Vector2(128, 159), Vector2(128, 155), Vector2(128, 156), Vector2(128, 156), Vector2(128, 156), Vector2(126, 159), Vector2(127, 159), Vector2(127, 160), Vector2(127, 159), Vector2(127, 158), Vector2(127, 158), Vector2(128, 158), Vector2(128, 157), Vector2(146, 150), Vector2(128, 153), Vector2(127, 154), Vector2(127, 153), Vector2(128, 157), Vector2(132, 157), Vector2(128, 157), Vector2(128, 157), Vector2(128, 158), Vector2(128, 158), Vector2(128, 158), Vector2(127, 158), Vector2(129, 157), Vector2(127, 162), Vector2(127, 163), Vector2(127, 164), Vector2(127, 163), Vector2(127, 162), Vector2(127, 157), Vector2(127, 159), Vector2(129, 155), Vector2(130, 160), Vector2(128, 159), Vector2(129, 160), Vector2(127, 156), Vector2(128, 159)],
		&"eric_bearhug_v2": [Vector2(127, 159), Vector2(128, 163), Vector2(129, 163), Vector2(128, 160), Vector2(128, 162), Vector2(128, 159), Vector2(131, 159), Vector2(128, 154), Vector2(128, 157), Vector2(128, 154), Vector2(128, 154), Vector2(130, 155), Vector2(128, 159), Vector2(124, 156), Vector2(128, 157)],
		&"eric_winded": [Vector2(128, 160), Vector2(128, 160), Vector2(128, 160), Vector2(128, 160)],
		&"eric_broken": [Vector2(126, 158), Vector2(131, 155), Vector2(120, 163), Vector2(126, 163), Vector2(126, 165), Vector2(129, 166), Vector2(130, 167), Vector2(129, 167)],
		&"eric_juggle": [null, null, null, null, null, null, null, null, null, null],
		&"eric_portal_charge": [Vector2(128, 163), Vector2(129, 163)],
	},
	&"mason": {
		&"mason_sheet": [Vector2(32, 40), Vector2(32, 41), Vector2(30, 40), Vector2(32, 41), Vector2(34, 40), Vector2(32, 41), Vector2(31, 44), Vector2(32, 40), Vector2(32, 40), Vector2(32, 41), Vector2(32, 40), Vector2(32, 41), Vector2(31, 44), Vector2(30, 45), Vector2(31, 50), Vector2(32, 41), Vector2(32, 44), Vector2(32, 42), Vector2(32, 40)],
		&"mason_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
	},
	&"josh": {
		&"josh_idle": [Vector2(42, 45), Vector2(42, 44), Vector2(42, 44), Vector2(42, 45)],
		&"josh_throw": [Vector2(40, 45), Vector2(47, 46), Vector2(46, 46), Vector2(42, 45)],
		&"josh_glide": [Vector2(49, 48), Vector2(49, 49), Vector2(49, 49), Vector2(49, 48)],
		&"josh_intro": [Vector2(42, 45), Vector2(42, 45), Vector2(42, 45), Vector2(42, 45), Vector2(42, 45), Vector2(44, 45)],
		&"josh_mount": [Vector2(42, 45), Vector2(47, 46), Vector2(49, 48)],
		&"josh_dismount": [Vector2(49, 51), Vector2(45, 52), Vector2(42, 45)],
		&"josh_recovery": [Vector2(49, 55), Vector2(49, 54), Vector2(49, 53), Vector2(49, 54)],
		&"josh_hit": [Vector2(39, 45), Vector2(40, 45)],
		&"josh_defeat": [Vector2(38, 45), Vector2(39, 48), Vector2(44, 52), Vector2(44, 57), Vector2(44, 57), Vector2(44, 57)],
		&"josh_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
	},
	&"carter": {
		&"carter_idle": [Vector2(48, 58), Vector2(48, 57), Vector2(48, 57), Vector2(48, 58)],
		&"carter_eye_flash": [Vector2(48, 58), Vector2(48, 58), Vector2(48, 58), Vector2(48, 58)],
		&"carter_rush": [Vector2(52, 63), Vector2(55, 61), Vector2(57, 59), Vector2(58, 59)],
		&"carter_rush_pass": [Vector2(55, 57), Vector2(53, 59), Vector2(51, 59)],
		&"carter_messatsu_charge": [Vector2(60, 63), Vector2(60, 63), Vector2(60, 63), Vector2(60, 63)],
		&"carter_messatsu_fire": [Vector2(60, 60), Vector2(41, 61), Vector2(41, 66)],
		&"carter_intro": [Vector2(47, 59), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(48, 51), Vector2(45, 50), Vector2(42, 58), Vector2(48, 58), Vector2(48, 58), Vector2(48, 58), Vector2(48, 58), Vector2(48, 58)],
		&"carter_spent": [Vector2(48, 71), Vector2(48, 70), Vector2(48, 70), Vector2(48, 71)],
		&"carter_hit": [Vector2(45, 58), Vector2(47, 58)],
		&"carter_defeat": [Vector2(48, 58), Vector2(47, 63), Vector2(46, 67), Vector2(46, 71), Vector2(47, 74), Vector2(47, 74)],
		&"carter_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
	},
	&"liam": {
		&"liam_channel": [Vector2(47, 56), Vector2(47, 56), Vector2(47, 55), Vector2(47, 55), Vector2(47, 56), Vector2(47, 56)],
		&"liam_blow": [Vector2(47, 56), Vector2(47, 55), Vector2(47, 57), Vector2(47, 57), Vector2(47, 56), Vector2(47, 56)],
		&"liam_ignite": [Vector2(47, 56), Vector2(47, 56), Vector2(47, 56), Vector2(47, 56), Vector2(47, 56)],
		&"liam_cast_left": [Vector2(47, 56), Vector2(47, 56), Vector2(47, 56)],
		&"liam_cast_right": [Vector2(47, 56), Vector2(47, 56), Vector2(47, 56)],
		&"liam_slam_rise": [Vector2(47, 57), Vector2(47, 59), Vector2(47, 57)],
		&"liam_wobble": [Vector2(45, 68), Vector2(47, 68), Vector2(49, 68), Vector2(47, 68)],
		&"liam_fall": [Vector2(56, 71), Vector2(42, 55), Vector2(43, 77), Vector2(48, 78)],
		&"liam_downed": [Vector2(48, 78), Vector2(49, 78), Vector2(48, 78)],
		&"liam_defeat": [Vector2(47, 68), Vector2(47, 72), Vector2(48, 78), Vector2(48, 74), Vector2(43, 77)],
		&"liam_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
	},
	&"bixby": {
		&"bixby_beast": [Vector2(95, 71), Vector2(95, 70), Vector2(95, 69), Vector2(95, 70)],
		&"bixby_beast_fly": [Vector2(104, 71), Vector2(104, 69), Vector2(104, 70)],
		&"bixby_beast_flyby": [Vector2(82, 60), Vector2(82, 60), Vector2(82, 60), Vector2(82, 60), Vector2(82, 60), Vector2(82, 60), Vector2(82, 60), Vector2(82, 60)],
		&"bixby_perch": [Vector2(95, 101), Vector2(95, 111), Vector2(95, 108), Vector2(95, 109), Vector2(95, 75), Vector2(95, 75), Vector2(95, 75), Vector2(95, 108), Vector2(95, 106), Vector2(95, 107), Vector2(95, 71), Vector2(95, 71), Vector2(95, 71), Vector2(95, 111), Vector2(95, 89), Vector2(95, 71)],
		&"bixby_pound": [Vector2(95, 70), Vector2(95, 71), Vector2(95, 77), Vector2(95, 90), Vector2(95, 84), Vector2(95, 74)],
		&"bixby_beast_land": [Vector2(95, 69), Vector2(95, 92), Vector2(95, 88)],
		&"bixby_beast_recover": [Vector2(96, 115), Vector2(95, 116), Vector2(95, 117), Vector2(104, 116)],
		&"bixby_beast_hit": [Vector2(95, 107), Vector2(95, 118)],
		&"bixby_juggle": [null, null, null, null, null, null, null, null, null, null, null, null],
		&"bixby_bite": [Vector2(95, 67), Vector2(95, 74), Vector2(95, 79), Vector2(95, 81), Vector2(95, 69)],
	},
}

# OVER: the back views. For each sheet (named as in BACK: its file name with no extension), the
# frames where his back faces the camera: the ring is drawn on his back there, at the BACK point,
# and the strings tie on OVER the sprite. On every other frame they run in under it.
const OVER := {
	"greyson_pose_a": [0, 1, 2],
	"greyson_pose_c": [0, 1, 2],
	"eric_sheet_v2": [15, 16, 17],
	"carter_rush_pass": [0, 1, 2],
	"carter_intro": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
}
