# Generated by art_source/jordan_puppeteer/jp_ship.py from the approved puppeteer rig (user approval
# 2026-09-28). Do not edit: change the rig and re-run it.
#
# Demon-god Jordan's puppeteer sheets (Assets/Characters/Jordan/God/jordan_god_puppeteer_*.png and
# jordan_god_hit.png, each with an _aura strip to add over it): every frame is 320x224, anchor texel
# (160, 223), placed as the hover is (the anchor texel's top-left corner on GOD_POINT, scale 3).
#
# TIPS[anim][frame] = {&"left": [5 x Vector2], &"right": [5 x Vector2]}: the claw-point texel each string
#   hangs from, in frame texels (x right, y down, the frame's bob included), in the order index, middle,
#   ring, little, thumb. &"left" is the screen-left hand (his right). A string starts at the texel's
#   centre: on screen, GOD_POINT + (tip + Vector2(0.5, 0.5) - Vector2(160, 223)) * 3.
# TENSION[anim][frame] = {&"left": float, &"right": float}: 0 slack .. 1 taut; a working hand is 0.7.
# TIMES[anim]: seconds per frame. NEXT[anim]: what plays after it, from frame NEXT_FRAME[anim] (the yanks
#   ride hover poses 0-3, so the control loop picks up on its frame 4).
# PAIRS[puppet]: the two TIPS indices its two strings leave from; both end on its back hook.
# RIFT[size]: the rift overlays in Rift/. Per frame, back draws behind the puppet, front in front of it,
#   glow is added over it; the anchor texel goes on the puppet's feet point, and the puppet is clipped at
#   the anchor row while it is in the rift. A loop is [first, last]: those frames repeat seamlessly while
#   a puppet is still rising or sinking.
# The strings (Strings/): puppet_string_blue.png is a 16x3 Line2D tile (glow, core, glow; one hot bead
#   for a pulse scrolled up the string), puppet_string_knot_blue.png a 5x5 glow to ADD on each fingertip.
#   Colours: core #66C6EC, glow #17385A (added), knot #2B6C99 (added), hot #D2F6FF.
# Every key in this file is a StringName.
extends RefCounted

const TIPS := {
	&"puppeteer_control": [
		{&"left": [Vector2(124, 64), Vector2(122, 59), Vector2(96, 57), Vector2(98, 65), Vector2(116, 57)],
			&"right": [Vector2(195, 64), Vector2(203, 61), Vector2(223, 57), Vector2(224, 64), Vector2(203, 57)]},
		{&"left": [Vector2(124, 62), Vector2(122, 56), Vector2(99, 56), Vector2(96, 62), Vector2(116, 54)],
			&"right": [Vector2(199, 66), Vector2(199, 61), Vector2(223, 57), Vector2(224, 65), Vector2(203, 57)]},
		{&"left": [Vector2(124, 61), Vector2(120, 56), Vector2(99, 55), Vector2(95, 60), Vector2(116, 53)],
			&"right": [Vector2(199, 65), Vector2(197, 58), Vector2(223, 56), Vector2(223, 64), Vector2(203, 56)]},
		{&"left": [Vector2(124, 61), Vector2(116, 58), Vector2(96, 54), Vector2(95, 61), Vector2(116, 54)],
			&"right": [Vector2(195, 61), Vector2(197, 56), Vector2(223, 54), Vector2(221, 62), Vector2(203, 54)]},
		{&"left": [Vector2(120, 65), Vector2(120, 60), Vector2(96, 56), Vector2(95, 64), Vector2(116, 56)],
			&"right": [Vector2(195, 61), Vector2(197, 55), Vector2(220, 55), Vector2(223, 61), Vector2(203, 53)]},
		{&"left": [Vector2(120, 66), Vector2(122, 59), Vector2(96, 57), Vector2(96, 65), Vector2(116, 57)],
			&"right": [Vector2(195, 62), Vector2(199, 57), Vector2(220, 56), Vector2(224, 61), Vector2(203, 54)]},
	],
	&"puppeteer_summon_both": [
		{&"left": [Vector2(129, 59), Vector2(122, 47), Vector2(97, 48), Vector2(92, 61), Vector2(114, 52)],
			&"right": [Vector2(190, 59), Vector2(197, 47), Vector2(222, 48), Vector2(227, 61), Vector2(205, 52)]},
		{&"left": [Vector2(117, 146), Vector2(108, 153), Vector2(97, 153), Vector2(89, 145), Vector2(107, 144)],
			&"right": [Vector2(202, 146), Vector2(211, 153), Vector2(222, 153), Vector2(230, 145), Vector2(212, 144)]},
		{&"left": [Vector2(117, 146), Vector2(111, 151), Vector2(104, 151), Vector2(98, 146), Vector2(111, 146)],
			&"right": [Vector2(202, 146), Vector2(208, 151), Vector2(215, 151), Vector2(221, 146), Vector2(208, 146)]},
		{&"left": [Vector2(120, 108), Vector2(115, 114), Vector2(107, 115), Vector2(101, 111), Vector2(114, 108)],
			&"right": [Vector2(199, 108), Vector2(204, 114), Vector2(212, 115), Vector2(218, 111), Vector2(205, 108)]},
		{&"left": [Vector2(120, 61), Vector2(117, 58), Vector2(100, 55), Vector2(98, 60), Vector2(117, 54)],
			&"right": [Vector2(199, 61), Vector2(202, 58), Vector2(219, 55), Vector2(221, 60), Vector2(202, 54)]},
		{&"left": [Vector2(123, 60), Vector2(121, 55), Vector2(96, 53), Vector2(94, 60), Vector2(115, 54)],
			&"right": [Vector2(196, 60), Vector2(198, 55), Vector2(223, 53), Vector2(225, 60), Vector2(204, 54)]},
		{&"left": [Vector2(124, 61), Vector2(122, 56), Vector2(96, 54), Vector2(95, 61), Vector2(116, 54)],
			&"right": [Vector2(195, 61), Vector2(197, 56), Vector2(223, 54), Vector2(224, 61), Vector2(203, 54)]},
	],
	&"puppeteer_summon_left": [
		{&"left": [Vector2(129, 59), Vector2(122, 47), Vector2(97, 48), Vector2(92, 61), Vector2(114, 52)],
			&"right": [Vector2(195, 63), Vector2(203, 60), Vector2(223, 56), Vector2(224, 63), Vector2(203, 56)]},
		{&"left": [Vector2(117, 146), Vector2(108, 153), Vector2(97, 153), Vector2(89, 145), Vector2(107, 144)],
			&"right": [Vector2(199, 67), Vector2(199, 62), Vector2(223, 58), Vector2(224, 66), Vector2(203, 58)]},
		{&"left": [Vector2(117, 146), Vector2(111, 151), Vector2(104, 151), Vector2(98, 146), Vector2(111, 146)],
			&"right": [Vector2(199, 67), Vector2(197, 60), Vector2(223, 58), Vector2(223, 66), Vector2(203, 58)]},
		{&"left": [Vector2(120, 108), Vector2(115, 114), Vector2(107, 115), Vector2(101, 111), Vector2(114, 108)],
			&"right": [Vector2(195, 62), Vector2(197, 57), Vector2(223, 55), Vector2(221, 63), Vector2(203, 55)]},
		{&"left": [Vector2(120, 61), Vector2(117, 58), Vector2(100, 55), Vector2(98, 60), Vector2(117, 54)],
			&"right": [Vector2(195, 60), Vector2(197, 54), Vector2(220, 54), Vector2(223, 60), Vector2(203, 52)]},
		{&"left": [Vector2(123, 60), Vector2(121, 55), Vector2(96, 53), Vector2(94, 60), Vector2(115, 54)],
			&"right": [Vector2(195, 61), Vector2(199, 56), Vector2(220, 55), Vector2(224, 60), Vector2(203, 53)]},
		{&"left": [Vector2(124, 61), Vector2(122, 56), Vector2(96, 54), Vector2(95, 61), Vector2(116, 54)],
			&"right": [Vector2(195, 63), Vector2(203, 60), Vector2(223, 56), Vector2(224, 63), Vector2(203, 56)]},
	],
	&"puppeteer_summon_right": [
		{&"left": [Vector2(124, 63), Vector2(122, 58), Vector2(96, 56), Vector2(98, 64), Vector2(116, 56)],
			&"right": [Vector2(190, 59), Vector2(197, 47), Vector2(222, 48), Vector2(227, 61), Vector2(205, 52)]},
		{&"left": [Vector2(124, 63), Vector2(122, 57), Vector2(99, 57), Vector2(96, 63), Vector2(116, 55)],
			&"right": [Vector2(202, 146), Vector2(211, 153), Vector2(222, 153), Vector2(230, 145), Vector2(212, 144)]},
		{&"left": [Vector2(124, 63), Vector2(120, 58), Vector2(99, 57), Vector2(95, 62), Vector2(116, 55)],
			&"right": [Vector2(202, 146), Vector2(208, 151), Vector2(215, 151), Vector2(221, 146), Vector2(208, 146)]},
		{&"left": [Vector2(124, 62), Vector2(116, 59), Vector2(96, 55), Vector2(95, 62), Vector2(116, 55)],
			&"right": [Vector2(199, 108), Vector2(204, 114), Vector2(212, 115), Vector2(218, 111), Vector2(205, 108)]},
		{&"left": [Vector2(120, 64), Vector2(120, 59), Vector2(96, 55), Vector2(95, 63), Vector2(116, 55)],
			&"right": [Vector2(199, 61), Vector2(202, 58), Vector2(219, 55), Vector2(221, 60), Vector2(202, 54)]},
		{&"left": [Vector2(120, 65), Vector2(122, 58), Vector2(96, 56), Vector2(96, 64), Vector2(116, 56)],
			&"right": [Vector2(196, 60), Vector2(198, 55), Vector2(223, 53), Vector2(225, 60), Vector2(204, 54)]},
		{&"left": [Vector2(124, 63), Vector2(122, 58), Vector2(96, 56), Vector2(98, 64), Vector2(116, 56)],
			&"right": [Vector2(195, 61), Vector2(197, 56), Vector2(223, 54), Vector2(224, 61), Vector2(203, 54)]},
	],
	&"puppeteer_yank_right": [
		{&"left": [Vector2(124, 64), Vector2(122, 59), Vector2(96, 57), Vector2(98, 65), Vector2(116, 57)],
			&"right": [Vector2(192, 69), Vector2(197, 60), Vector2(223, 60), Vector2(227, 70), Vector2(205, 64)]},
		{&"left": [Vector2(124, 62), Vector2(122, 56), Vector2(99, 56), Vector2(96, 62), Vector2(116, 54)],
			&"right": [Vector2(211, 60), Vector2(193, 54), Vector2(189, 59), Vector2(189, 66), Vector2(207, 55)]},
		{&"left": [Vector2(124, 61), Vector2(120, 56), Vector2(99, 55), Vector2(95, 60), Vector2(116, 53)],
			&"right": [Vector2(212, 61), Vector2(196, 53), Vector2(190, 57), Vector2(189, 63), Vector2(209, 55)]},
		{&"left": [Vector2(124, 61), Vector2(116, 58), Vector2(96, 54), Vector2(95, 61), Vector2(116, 54)],
			&"right": [Vector2(195, 58), Vector2(197, 53), Vector2(222, 51), Vector2(224, 57), Vector2(203, 52)]},
	],
	&"puppeteer_yank_left": [
		{&"left": [Vector2(127, 69), Vector2(122, 60), Vector2(96, 60), Vector2(92, 70), Vector2(114, 64)],
			&"right": [Vector2(195, 64), Vector2(203, 61), Vector2(223, 57), Vector2(224, 64), Vector2(203, 57)]},
		{&"left": [Vector2(108, 60), Vector2(126, 54), Vector2(130, 59), Vector2(130, 66), Vector2(112, 55)],
			&"right": [Vector2(199, 66), Vector2(199, 61), Vector2(223, 57), Vector2(224, 65), Vector2(203, 57)]},
		{&"left": [Vector2(107, 61), Vector2(123, 53), Vector2(129, 57), Vector2(130, 63), Vector2(110, 55)],
			&"right": [Vector2(199, 65), Vector2(197, 58), Vector2(223, 56), Vector2(223, 64), Vector2(203, 56)]},
		{&"left": [Vector2(124, 58), Vector2(122, 53), Vector2(97, 51), Vector2(95, 57), Vector2(116, 52)],
			&"right": [Vector2(195, 61), Vector2(197, 56), Vector2(223, 54), Vector2(221, 62), Vector2(203, 54)]},
	],
	&"hit": [
		{&"left": [Vector2(129, 68), Vector2(122, 58), Vector2(98, 58), Vector2(93, 69), Vector2(115, 63)],
			&"right": [Vector2(190, 68), Vector2(197, 58), Vector2(221, 58), Vector2(226, 69), Vector2(204, 63)]},
		{&"left": [Vector2(127, 63), Vector2(124, 55), Vector2(97, 53), Vector2(94, 62), Vector2(116, 56)],
			&"right": [Vector2(192, 63), Vector2(195, 55), Vector2(222, 53), Vector2(225, 62), Vector2(203, 56)]},
	],
}

const TENSION := {
	&"puppeteer_control": [
		{&"left": 0.7, &"right": 0.7}, {&"left": 0.7, &"right": 0.7}, {&"left": 0.7, &"right": 0.7},
		{&"left": 0.7, &"right": 0.7}, {&"left": 0.7, &"right": 0.7}, {&"left": 0.7, &"right": 0.7},
	],
	&"puppeteer_summon_both": [
		{&"left": 0.5, &"right": 0.5}, {&"left": 0.0, &"right": 0.0}, {&"left": 0.3, &"right": 0.3},
		{&"left": 1.0, &"right": 1.0}, {&"left": 1.0, &"right": 1.0}, {&"left": 0.85, &"right": 0.85},
		{&"left": 0.7, &"right": 0.7},
	],
	&"puppeteer_summon_left": [
		{&"left": 0.5, &"right": 0.7}, {&"left": 0.0, &"right": 0.7}, {&"left": 0.3, &"right": 0.7},
		{&"left": 1.0, &"right": 0.7}, {&"left": 1.0, &"right": 0.7}, {&"left": 0.85, &"right": 0.7},
		{&"left": 0.7, &"right": 0.7},
	],
	&"puppeteer_summon_right": [
		{&"left": 0.7, &"right": 0.5}, {&"left": 0.7, &"right": 0.0}, {&"left": 0.7, &"right": 0.3},
		{&"left": 0.7, &"right": 1.0}, {&"left": 0.7, &"right": 1.0}, {&"left": 0.7, &"right": 0.85},
		{&"left": 0.7, &"right": 0.7},
	],
	&"puppeteer_yank_right": [
		{&"left": 0.7, &"right": 0.2}, {&"left": 0.7, &"right": 1.0}, {&"left": 0.7, &"right": 1.0},
		{&"left": 0.7, &"right": 0.8},
	],
	&"puppeteer_yank_left": [
		{&"left": 0.2, &"right": 0.7}, {&"left": 1.0, &"right": 0.7}, {&"left": 1.0, &"right": 0.7},
		{&"left": 0.8, &"right": 0.7},
	],
	&"hit": [
		{&"left": 1.0, &"right": 1.0}, {&"left": 0.6, &"right": 0.6},
	],
}

const TIMES := {
	&"puppeteer_control": [0.14, 0.14, 0.14, 0.14, 0.14, 0.14],
	&"puppeteer_summon_both": [0.1, 0.08, 0.16, 0.05, 0.14, 0.14, 0.1],
	&"puppeteer_summon_left": [0.1, 0.08, 0.16, 0.05, 0.14, 0.14, 0.1],
	&"puppeteer_summon_right": [0.1, 0.08, 0.16, 0.05, 0.14, 0.14, 0.1],
	&"puppeteer_yank_right": [0.06, 0.05, 0.12, 0.08],
	&"puppeteer_yank_left": [0.06, 0.05, 0.12, 0.08],
	&"hit": [0.08, 0.16],
}

const NEXT := {
	&"puppeteer_control": &"puppeteer_control",
	&"puppeteer_summon_both": &"puppeteer_control",
	&"puppeteer_summon_left": &"puppeteer_control",
	&"puppeteer_summon_right": &"puppeteer_control",
	&"puppeteer_yank_right": &"puppeteer_control",
	&"puppeteer_yank_left": &"puppeteer_control",
	&"hit": &"puppeteer_control",
}

const NEXT_FRAME := {
	&"puppeteer_control": 0,
	&"puppeteer_summon_both": 0,
	&"puppeteer_summon_left": 0,
	&"puppeteer_summon_right": 0,
	&"puppeteer_yank_right": 4,
	&"puppeteer_yank_left": 4,
	&"hit": 0,
}

const PAIRS := {&"greyson": [0, 1], &"matt": [2, 3], &"burak": [2, 3], &"danny": [2, 3]}

const RIFT := {
	&"standard": {
		&"size": Vector2(144, 96), &"anchor": Vector2(72, 72),
		&"summon_times": [0.08, 0.08, 0.1, 0.1, 0.1, 0.1, 0.08, 0.12], &"summon_loop": [3, 5],
		&"despawn_times": [0.06, 0.08, 0.12, 0.12, 0.08, 0.14], &"despawn_loop": [2, 3],
		&"puppets": [&"greyson", &"matt", &"burak"],
		&"sheets": {
			&"summon_back": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_summon_back.png",
			&"summon_front": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_summon_front.png",
			&"summon_glow": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_summon_glow.png",
			&"despawn_back": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_despawn_back.png",
			&"despawn_front": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_despawn_front.png",
			&"despawn_glow": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_despawn_glow.png",
		},
	},
	&"wide": {
		&"size": Vector2(224, 112), &"anchor": Vector2(112, 84),
		&"summon_times": [0.08, 0.08, 0.1, 0.1, 0.1, 0.1, 0.08, 0.12], &"summon_loop": [3, 5],
		&"despawn_times": [0.06, 0.08, 0.12, 0.12, 0.08, 0.14], &"despawn_loop": [2, 3],
		&"puppets": [&"danny"],
		&"sheets": {
			&"summon_back": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_wide_summon_back.png",
			&"summon_front": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_wide_summon_front.png",
			&"summon_glow": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_wide_summon_glow.png",
			&"despawn_back": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_wide_despawn_back.png",
			&"despawn_front": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_wide_despawn_front.png",
			&"despawn_glow": "res://Assets/Characters/Jordan/God/Rift/puppet_rift_wide_despawn_glow.png",
		},
	},
}
